Pertemuan ke-5 
Pada tugas kali ini ada 5 materi yang akan coba. Materi dari 5.16 List 2 Dimensi hingga materi 5.20 Numpy

5.16
LIST 2 DIMENSI = List 2 dimensi biasanya digunakan untuk menyimpan struktur data yang kompleks seperti tabel, matriks

In [9]:
#latihan penerapan list 2 dimensi pada python
#list buah dengan 2 dimensi 
buah = [
    ["mangga", "melon", "pepaya"],
    ["nanas", "apel", "jeruk"],
    ["anggur", "klengkeng", "srikaya"]
]

#misalkan saya ingin menampilkan semua isi dalam list 2 dimensi (buah), maka kode nya adalah
print(buah)

#misalkan saya ingin menampilkan baris kedua dalam list 2 dimensi (buah), maka kode nya adalah
buah[2]

[['mangga', 'melon', 'pepaya'], ['nanas', 'apel', 'jeruk'], ['anggur', 'klengkeng', 'srikaya']]


['anggur', 'klengkeng', 'srikaya']

In [10]:
#misalkan saya ingin mengambil 'klengkeng'
buah[2][1]
#angka dua pada kode diatas menunjukkan indeks list yang akan kita akses yaitu pada baris kedua
#kemudian setelah dapat list nya baru akan mengambil isinya yaitu pada kolom ke 1

'klengkeng'

In [12]:
buah[1][0]="stroberi"
print(buah[1][0])
#mengganti kata "nanas" yang terletak pada indeks baris ke 2 kolom ke 0 dengan kata "stroberi"

buah
#lalu kode ini untuk memanggil isi list kembali dengan kalimat yang baru sesuai dengan kalimat yang telah diganti

stroberi


[['mangga', 'melon', 'pepaya'],
 ['stroberi', 'apel', 'jeruk'],
 ['anggur', 'klengkeng', 'srikaya']]

In [15]:
#memanggil anggota dari list buah
for baris in buah:
    print(baris)
    #menampilkan baris pada list buah
    for kolom in baris:
        print(kolom)
    #menampilkan kolom sesuai urutan baris

['mangga', 'melon', 'pepaya']
mangga
melon
pepaya
['stroberi', 'apel', 'jeruk']
stroberi
apel
jeruk
['anggur', 'klengkeng', 'srikaya']
anggur
klengkeng
srikaya


In [16]:
#lalu kita juga bisa memanggil isi list menggunakan for loop
for seger in buah:
    print(seger)

['mangga', 'melon', 'pepaya']
['stroberi', 'apel', 'jeruk']
['anggur', 'klengkeng', 'srikaya']


5.17
TUPLES = Tuples berfungsi untuk menampung sekumpulan data hampir sama dengan list, perbedaan tuples dengan list adalah kurung yang digunakan berbeda dan tipe data tuples bersifat tidak dapat diubah yang berarti elemen pada tipe data tuples tidak dapat diubah setelah proses pendeklarasiannya. Tipe data ini diawali dengan tanda kurung buka "(", memisahkan setiap elemen di dalamnya dengan tanda koma ( , ), penulisan nilai menggunakan "" dan ditutup dengan tanda kurung tutup ")".

In [22]:
#latihan penerapan tuples pada python

#contoh isi data tuples adalah hewan
hewan = ("kucing", "marmut", "kelinci", "panda")

#jika ingin memanggil isi tuples semua adalah menggunakan
print(hewan)

#memanggil indeks pada posisi ke 1
print(hewan[1])

#memanggil urutan isi data tuples dari posisi indeks ke 0 sampai dengan 2
#posisi indeks ke 2 tidak akan ikut karna aturan dalam python begitu
print(hewan[0:2])

#kita juga bisa memanggil isi tuples menggunakan for looping
#memanggil urutan isi data tuples dari 0 sampai 4 
#dengan aturan pada python posisi indeks ke 4 tidak akan ikut
for lucu in hewan[0:4]:
    print(lucu)

('kucing', 'marmut', 'kelinci', 'panda')
marmut
('kucing', 'marmut')
kucing
marmut
kelinci
panda


In [28]:
hewan["panda"]="rusa"
#program tidak akan bisa berjalan atau akan adanya error karena tuples tidak bisa melakukan penggantian data

TypeError: 'tuple' object does not support item assignment

In [31]:
hewan.append("rusa")
#program tidak akan bisa berjalan atau akan adanya error karena tuples tidak bisa menambahkan nilai baru dalam data

AttributeError: 'tuple' object has no attribute 'append'

In [32]:
hewan.remove("kucing")
#program tidak akan bisa berjalan atau akan adanya error karena tuples tidak bisa menghapus data

AttributeError: 'tuple' object has no attribute 'remove'

In [36]:
hewan.count("kucing")
#Fungsi count ini berguna untuk menghitung beberapa kali kata "kucing" yang hadir dalam tuple

1

In [37]:
hewan.index("kelinci")
#Fungsi index ini berguna untuk menemukan posisi indeks tertentu di hewan pada tupel

2

5.18
DICTIONARIES = Dictionary adalah tipe data pada python yang berfungsi untuk menyimpan kumpulan data/nilai dengan pendekatan “key-value”. Dictionary sendiri memiliki 3 sifat yaitu 
-ia tidak berurutan (sehingga key yang pertama kali kita definisikan, tidak berarti dia akan benar-benar menjadi yang “pertama” dibandingkan dengan key yang lainnya), 
-lalu kita bisa kita mengubah value yang telah kita masukkan ke dalam sebuah dictionary
-dan dictionary tidak bisa memiliki lebih dari satu key yang sama

In [4]:
#latihan membuat dictionary
#kita bisa mendeklarasikan menggunakan tanda kurung kurawa {}
data = {
    "nama" : "Uswatun Miftahul Jannah",
    "univ" : "Universitas Udayana",
    "fakultas" : "Fakultas MIPA"
}

In [10]:
#kita bisa memanggil isi data dengan:
print(data)

#kita juga bisa memanggil hanya nama nya saja
print(data["nama"])

#akan terjadi error disini karna key nya salah yang bener harusnya "nama"
print(data["Nama"])

{'nama': 'Uswatun Miftahul Jannah', 'univ': 'Universitas Udayana', 'fakultas': 'Fakultas MIPA'}
Uswatun Miftahul Jannah


KeyError: 'Nama'

In [11]:
#kelebihan fungsi get adalah kita bisa mengatur nilai default jika key pada dictionary yang kita panggil tidak ditemukan 
#hal itu akan mencegah sistem untuk menampilkan error
print(data.get('nama'))

Uswatun Miftahul Jannah


In [12]:
print(data.get('tanggal_lahir'))
#data tanggal lahir tdak akan ditemukan karna tidak tidak ada key tanggal lahir di data

None


In [14]:
print(data.get('tanggal_lahir','27-10-2003'))

#jika kita menggunakan get data tanggal lahir tidak akan masuk kedalam data dictionary
#jadi sifat data tanggal lahir adalah tidak permanen
print(data)

27-10-2003
{'nama': 'Uswatun Miftahul Jannah', 'univ': 'Universitas Udayana', 'fakultas': 'Fakultas MIPA'}


In [15]:
print(data['tanggal_lahir'])
#dan data tanggal lahir tidak bisa di panggil disni

KeyError: 'tanggal_lahir'

In [18]:
#disini kita akan menambahkan data baru
data['tanggal_lahir'] = '27-10-2003'
#lalu kita print ulang
print(data)

{'nama': 'Uswatun Miftahul Jannah', 'univ': 'Universitas Udayana', 'fakultas': 'Fakultas MIPA', 'tanggal_lahir': '27-10-2003'}


5.19
Fungsi dalam Python = fungsi dalam python merupakan kumpulan perintah yang dikelompokkan menjadi satu, fungsi yang telah dibuat  ini nantinya akan bisa dipanggil serta digunakan berulang kali

In [21]:
#dalam python sintaks pembuatan fungsi terlihat seperti berikut:
def full_nama(first_name,last_name):
    print(f"Nama lengkapnya anda adalah {first_name} {last_name}")

#kata kunci def yang menjadi pertanda bahwa blok kode program adalah sebuah fungsi
#lalu setelah itu ada nama fungsi yang kita buat
#selanjutnya yang didalam kurung adalah parameters yang akan diterima oleh fungsi yang kita buat
#lalu dibawahnya ada blok kode fungsi yang di sana akan kita tulis perintah-perintah yang harus dilakukan oleh sebuah fungsi

In [22]:
#contoh sebuah fungsi
first_name = input("Nama depan anda adalah ")
last_name = input ("Nama belakang anda adalah ")
full_nama(first_name, last_name)

Nama depan anda adalah Uswatun
Nama belakang anda adalah Miftahul
Nama lengkapnya anda adalah Uswatun Miftahul


5.20
NUMPY adalah library Python yang fokus pada scientific computing
Numpy menyediakan fungsi yang siap pakai untuk memudahkan kita melakukan perhitungan saintifik seperti matriks, aljabar, statistik, dan sebagainya.

In [29]:
#hal pertama yg dilakukan adalah kita memanggil library numpy
import numpy as np

5.20.1 Perintah Dasar pada Numpy

In [39]:
#latihan pertama kita membuat array dengan numpy

#contoh np array 1 baris
lat_1 = np.array([0,1,2,3,4])

#mengakses data pada array
print(lat_1)

#contoh np array 2 baris
lat_2 = np.array([[5,6,7,8],[9,10,11,12]])
print(lat_2)

#contoh np array 3 baris
lat_3 = np.array([[[0,1,2,3],[4,5,6,7]],
              [[8,9,10,11],[12,13,14,15]],
              [[16,17,18,19],[19,20,21,22]]])
print(lat_3)

[0 1 2 3 4]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [19 20 21 22]]]


In [40]:
#mengetahui banyaknya dimensi dari variabel lat_1
lat_1.ndim

1

In [41]:
#mengetahui banyaknya dimensi dari variabel lat_2
lat_2.ndim

2

In [42]:
#mengetahui banyaknya dimensi dari variabel lat_3
lat_3.ndim

3

In [43]:
#untuk mengetahui bentuk/shape dari variabel lat_1
lat_1.shape

(5,)

In [44]:
#untuk mengetahui bentuk/shape dari variabel lat_2
lat_2.shape

(2, 4)

out menghasilkan (2,4) yang artinya variabel lat_2 berbentuk atau mempunyai 2 indeks kesamping dan setiap indeks mempunyai 4 anggota

In [45]:
#untuk mengetahui bentuk/shape dari variabel lat_3
lat_3.shape

(3, 2, 4)

out menghasilkan (3,2,4) yang artinya variabel lat_3 berbentuk atau mempunyai 3 baris dengan 2 indeks kesamping dan setiap indeks mempunyai 4 anggota

5.20.2 Memanggil Anggota, Kolom dan Baris dengan Numpy

In [46]:
#membuat array dengan numpy
lat_4 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

#cara mengakses datanya
print(lat_4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [48]:
#misal saya ingin mengambil angka 8, maka bisa diakses dengan:
#ingat list atau array indeks nya selalu dimulai dari 0
lat_4[1,3]

#karna angka 8 berada didalam baris ke 1 dan kolom ke 3

8

In [50]:
lat_4[1,:]
#kode ini untuk menampilkan isi array pada baris ke 1

array([5, 6, 7, 8])

In [52]:
lat_4[:,2]
#kode ini untuk menampilkan isi array pada kolom ke 2

array([ 3,  7, 11])

In [53]:
lat_4[1,1:4]
#kode ini untuk menampilkan isi array pada baris ke 1 
#dimulai dari indeks ke 1 sampai dengan ke 4, dengan posisi indeks yang ke 4 tidak ikut

array([6, 7, 8])

In [55]:
lat_4[2,0:4:2]
#kode ini untuk menampilkan isi array pada baris ke 2
#dimulai dari indeks ke 0 sampai dengan ke 4, dengan kelipatan 2

array([ 9, 11])

In [57]:
lat_4[0,0] = 80
#kode ini untuk mengubah isi didalam array pada baris ke 0 dan kolom ke 0
#yang sebelumnya angka 0 kita ubah menjadi angka 80

print(lat_4)
#lalu kita akses datanya

[[80  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


5.20.3 Matriks pada Numpy

In [65]:
#array multidimensi
#np.ones() digunakan untuk membuat array dengan anggota bernilai 1
a = np.ones((3,2))
print(a)

#array satu dimensi
#np.zeros() digunakan untuk membuat array dengan anggota bernilai 0
b = np.zeros(5)
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0. 0. 0. 0. 0.]


In [68]:
c = np.identity(5)
print(c)
#np.identity adalah matriks bujur sangkar yang semua elemen diagonal utamanya adalah 1 dan semua elemen lainnya sama dengan 0

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [69]:
d = 8*c
print(d)
#kode ini untuk mengubah diagonal utama di dalam matriks bujur sangkar yang ada pada int [68]
#mengubah diagonal utama nya 1 menjadi 8

[[8. 0. 0. 0. 0.]
 [0. 8. 0. 0. 0.]
 [0. 0. 8. 0. 0.]
 [0. 0. 0. 8. 0.]
 [0. 0. 0. 0. 8.]]


In [70]:
np.full((2,3),8)
#np.full digunakan untuk membuat array dengan isinya adalah
#2 baris, 3 kolom, dengan anggota bernilai 8

array([[8, 8, 8],
       [8, 8, 8]])

In [72]:
np.random.rand(2,3)
#np.random.rand digunakan untuk membuat array bentuk tertentu dan mengisinya dengan nilai acak
#disini (2,3) yang artinya 2 baris,3 kolom dengan anggota nilai acak

array([[0.80414441, 0.34619784, 0.13222024],
       [0.53112044, 0.4590812 , 0.67890279]])

In [73]:
np.random.randint(1,10,size=(3,4))
#np.random.randint digunakan untuk melakukan random sampling di numpy.
#Ini mengembalikan array dengan bentuk yang ditentukan dan mengisinya dengan bilangan bulat acak dari rendah (inklusif) hingga tinggi (eksklusif), yaitu dalam interval.
#size : bentuk keluaran. Disini saya menulis size (3,4) yang artinya 3 baris dengan 4 kolom

array([[7, 7, 8, 4],
       [4, 9, 1, 4],
       [6, 7, 1, 4]])

5.20.4 Copy pada Numpy

In [ ]:
import numpy as np

In [2]:
a = np.array([2,3,4,5])
print(a)

[2 3 4 5]


In [4]:
#awalnya, array 'a' dibuat dengan nilai [2, 3, 4, 5] 
#kemudian, referensi ke 'a' ditetapkan ke 'b' 
b = a
print(b)

#dan salinan 'a' dibuat menggunakan np.copy() dan ditetapkan ke 'c'
c = np.copy(a)
print(c)

[2 3 4 5]
[2 3 4 5]


In [5]:
b[1] = 8
print(b)
print(a)

##kode ini untuk mengubah nilai elemen ke 1 'b' menjadi 8, nilai tersebut juga tercermin dalam 'a' 
#karena 'a' hanyalah referensi ke lokasi memori yang sama dengan 'b'. Jadi, 'a' juga mengandung [2, 8, 4 5]

[2 8 4 5]
[2 8 4 5]


In [10]:
print(c)
#salinan 'c' tidak terpengaruh oleh perubahan 'b' karena merupakan salinan yang dalam dan memiliki lokasi memori tersendiri. 
#Jadi, 'c' berisi nilai asli [2, 3, 4, 5]

[2 3 4 5]


5.20.5 Operasi Matematika pada Numpy

In [18]:
a = np.array([1,2,3,4])
a+2
#untuk operasi penjumlahan array a ditambahkan 2

array([3, 4, 5, 6])

In [21]:
a-2
#untuk operasi pengurangan array a dikurang 2

array([-1,  0,  1,  2])

In [22]:
a*2
#untuk operasi perkalian array a dikali 2

array([2, 4, 6, 8])

In [23]:
a/2
#untuk operasi pembagian array a dibagi 2

array([0.5, 1. , 1.5, 2. ])

In [24]:
a**2
#untuk operasi pangkat array a pangkat 2

array([ 1,  4,  9, 16])

In [25]:
b = np.array([5,6,7,8])
a+b
#untuk operasi penjumlahan array a ditambah array b

array([ 6,  8, 10, 12])

In [26]:
a-b
#untuk operasi pengurangan array a dikurang array b

array([-4, -4, -4, -4])

In [27]:
a*b
#untuk operasi perkalian array a dikali array b

array([ 5, 12, 21, 32])

In [28]:
a/b
#untuk operasi pembagian array a dibagi array b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [29]:
b**a
#untuk operasi pangkat array b ber pangkat array a

array([   5,   36,  343, 4096])

In [31]:
np.cos(0)
#latihan ini saya menggunakan np.cos untuk menghitung cosinus dari 0, yaitu 1.

1.0

5.20.6 Perkalian Matriks pada Numpy

In [36]:
#lat ini saya akan membuat 2 matriks berukuran 2x4
x = np.array([[1,2,3,4],[5,6,7,8]])
print(x)
y = np.array([[9,10,11,12],[13,14,15,16]])
print(y)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]


In [39]:
c = x*y
#untuk perkalian dua buah matriks yaitu matriks x dengan matriks y
print(c)

[[  9  20  33  48]
 [ 65  84 105 128]]


In [1]:
d = np.matmul(x,y)
print(d)
#terjadi error disini karna matriks ordo 2x4 tidak bisa dikalikan dengan matriks ordo 2x4

NameError: name 'np' is not defined

In [41]:
e = np.array([[9,10],[11,12],[13,14],[15,16]])
print(e)

[[ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [43]:
f = np.matmul(a,e)
print(f)
#perkalian matriks a dengan matriks e

[130 140]


5.20.7 min, max, dan sum pada Numpy

In [44]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [45]:
b = np.min(a)
print(b)

#np.min digunakan untuk mencari nilai minium dari array a

1


In [49]:
c = np.min(a,axis=0)
print(c)
#bila axis=0 maka akan mengoperasikan baris saja
#artinya baris bilangan terkecil dari array a

[1 2 3 4]


In [51]:
d = np.min(a,axis=1)
print(d)
#bila axis=1 maka akan mengoperasikan kolom saja
#artinya kolom bilangan terkecil dari array a

[1 5 9]


In [52]:
e = np.max(a)
print(e)

#np.max digunakan untuk mencari nilai maksimum dari array a

12


In [54]:
f = np.max(a,axis=0)
print(f)
#bila axis=0 maka akan mengoperasikan baris saja
#artinya baris bilangan terbesar dari array a

[ 9 10 11 12]


In [55]:
g = np.max(a,axis=1)
print(g)
#bila axis=1 maka akan mengoperasikan kolom saja
#artinya kolom bilangan terbesar dari array a

[ 4  8 12]


In [57]:
h = np.sum(a)
print(h)

#np.sum digunakan untuk menjumlahkan semua bilangan yang berada di dalam array a

78


In [58]:
i = np.sum(a,axis=0)
print(i)
#digunakan untuk menjumlahkan setiap baris pada array a

[15 18 21 24]


In [59]:
j = np.sum(a,axis=1)
print(j)
#digunakan untuk menjumlahkan setiap kolom pada array a

[10 26 42]
